### ISSUE TITLE
Misleading ReadMe

### ISSUE THREAD

**Issue by s-kesh** [shivaprsdv/mathdown#1]
> Most minimal github flavoured markdown editor

How you can claim that?
Lets count problem in your code

* Python (it is not minimal)
* Javascript (wow! how minimal)
* You need pywebview, bottle and other modules.
* Writing text in browser. As browser is such a minimal piece of software.
* An web app (minimal? aaa tuh)

First of all, you don't know what is minimal software.

And on second note, I am tring to use it by running mathdown.html on firefox.
How can I save pdf out of that? even text file?

On third note, Please remove _minimal_ from your readme file.

**Comment by shivaprsd** [comment]
First of all, you don't read. Do you know how to read? Read:
> The most minimalistic *GitHub-flavoured MarkDown editor, with MathJax support with LaTeX/AsciiMath input*

There. I am not claiming it is the *most minimalistic software ever written*. I mean a specific software. If you check out all the *'GitHub-flavoured MarkDown editor, with MathJax support'* out there, you will know what I mean. And none of them seem to have *'AsciiMath input'*.

Anyway, by *minimal* I don't mean *'minimal program design'*; I mean *'minimal user interface'*. That doesn't mean anything to you, so shut up.

> And on second note, I am tring to use it by running mathdown.html on firefox.

Don't do that. You won't probably be allowed to load local resources (e.g. images) due to security restrictions. Python code exists to give you a local web-server. If you don't want pywebview, remove 2nd and last lines from `mathdown.py`, do `python mathdown.py` and point Firefox to `localhost:8000`.

> How can I save pdf out of that?

Just do `Ctrl+P` and `Save to pdf`. That is what I mean by minimal. No bloat, use system feature.

**Comment by shivaprsd** [comment]
And yeah, all the Python, bottle, browser and some part of JavaScript is needed only for live editing ~~and rendering~~. I can strip all that down and create a command-line version just like Tex Live, which might be what *you* call minimal. But I don't have time now, sorry.

**Comment by s-kesh** [comment]
> Just do `Ctrl +P` and `Save to pdf`

What about text file. I need a `shivaprasadhattsalle.mardown`, so I can convert that to html latter.

> And yeah, all the Javascript, bottle, browser and some part of Python is needed only for live editing and rendering. I can strip all that down and create a command-line version just like Tex Live, which might be what you call minimal. But I don't have time now, sorry.

Yes this is what I prefer. I prefer to type markdown in any editor and just a binary file to convert that to pdf/html on go. Should I assume that this software is not longer developed?

**Comment by shivaprsd** [comment]
> What about text file.

Text file of what? If you mean what you type in the editor, you can just plain copy and save it in a `.md` file using any text editor. If you want the html code of the output, well.. you will have to use Developer tools.

> Should I assume that this software is not longer developed?

That's right. Not at the moment. But let me see; if it is not much work I'll do it in my free time.

**Comment by shivaprsd** [comment]
Done. Checkout the `cli` branch: 271f0c2. Execute `mathdown.sh`

**Comment by s-kesh** [comment]
> checkout the cli branch

Nice commit btw. I am closing this issue as our lord **Shiva Prasad Bhaiya** has solved my issue using just a simple sed line.
